name: Build and Release

on:
  push:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: beta

      - name: Install packages and compile exe
        run: |
          dart pub get
          dart compile aot-snapshot bin/main.dart
          dart compile jit-snapshot bin/main.dart
          dart compile exe bin/main.dart

      - name: Compile kernel
        if: matrix.os == 'ubuntu-latest'
        run: dart compile kernel bin/main.dart

      - name: Archive kernel
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: bin/main.dill

      - name: Rename
        shell: pwsh
        run: |
          Remove-Item * -Include '*.dart','*.dill' -Recurse
          Get-ChildItem -Recurse main.* | Rename-Item -NewName { $_.Name -replace 'main.','main-${{ runner.os }}-${{ runner.arch }}.' }

      - name: Zip
        shell: pwsh
        run: |
          Move-Item -Path * -Exclude bin,lib -Destination 'rm' -Force
          Remove-Item -Path 'rm' -Recurse -Force
          Compress-Archive . -DestinationPath '${{ runner.os }}-${{ runner.arch }}.zip' -Force

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: ${{ runner.os }}-${{ runner.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          name: Release ${{ github.run_id }}
          files: |
            **/*.dill
            **/*.zip
